<section id="facebook-fans">
	<h1>Fans på <b>Facebook</b></h1>
	<ul>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
		<li><a href=""><img src="" alt="" /></a></li>
	</ul>
	<p>
		<strong>9387</strong> er fan av Slagkraft <br />
		- <a href="#">bli fan du også!</a>
	</p>
</section>