<section id="twitter-updates">
	<h1><?php echo $_GET['page'] === 'artist' ? 'Tolv Volt' : 'Snakk på'; ?> <b>Twitter</b> <span class="twitterbird"></span></h1>
	<ul>
		<li>
			<h2><a href="#">Aamann</a></h2>
			<p>
				<span>-</span>
				Takka nei til en invitasjon fra en festival i Israel. Nok er nok 
			</p>
		</li>
		<li>
			<h2><a href="#">MTV_Denmark</a></h2>
			<p>
				<span>-</span>
				Gør en trist mandag mindre trist - vind billetter til årets Roskilde Festival på MTV.dk!
			</p>
		</li>
		<li>
			<h2><a href="#">kenspo</a></h2>
			<p>
				<span>-</span>
				RT <a href="#">@sjefsengel</a>: Hovefestivalen mangler flere frivillige voksne - så er de i mål. Vil DU være med? <a href="#">http://bit.ly/bwut67</a>  
			</p>
		</li>
		<?php if ($tname !== 'frontpage') { ?>
			<li>
				<h2><a href="#">iRelateToThis</a></h2>
				<p>
					<span>-</span>
					Torturing yourself with depressing music when you're already feeling sad.
				</p>
			</li>
			<li>
				<h2><a href="#">Aamann</a></h2>
				<p>
					<span>-</span>
					Takka nei til en invitasjon fra en festival i Israel. Nok er nok 
				</p>
			</li>
			<li>
				<h2><a href="#">jason_mraz</a></h2>
				<p>
					<span>-</span>
					Author Kurt Vonnegut once mentioned that his epitaph should read, "The only proof he needed for the existance of God was music."
				</p>
			</li>
		<?php } ?>
	</ul>	
</section>