<section id="respond">
	<h3>Legg til <b>kommentar</b></h3>			
	<form action="">
		<div class="rules">
			<p>Fyll inn din personlige info til venstre eller identifiser deg med Twitter eller Facebook.</p>
			<fieldset class="connectframe">
				<button class="connect facebook">Koble til med Facebook</button><br />
				<button class="connect twitter">Koble til med Twitter</button>
			</fieldset>
			<p>Gravatar er støttet, om e-post er utfylt.</p>
		</div>
		<fieldset class="form">
			<ul>
				<li class="name">
					<label>
						<span>Ditt navn <small>(påkrevd)</small></span>
						<input type="text" />
					</label>
				</li>
				<li class="email">
					<label>
						<span>Din e-post <small>(ikke synlig)</small></span>
						<input type="email" />
					</label>
				</li>
				<li class="message">
					<label>
						<span>Din melding <small>(påkrevd, maks 300 tegn)</small></span>
						<textarea></textarea>
					</label>
				</li>
			</ul>
			<input type="submit" value="Send"/>
		</fieldset>
	</form>
</section>